//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.11 at 07:54:45 PM IST 
//


package com.vms.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "driverAttendanceCons"
})
@XmlRootElement(name = "driverAttendanceList")
public class DriverAttendanceConsolidateListDTO {

    protected List<DriverAttendanceConsolidateDTO> driverAttendanceCons;

    public List<DriverAttendanceConsolidateDTO> getDriverAttendanceList() {
        if (driverAttendanceCons == null) {
            driverAttendanceCons = new ArrayList<DriverAttendanceConsolidateDTO>();
        }
        return this.driverAttendanceCons;
    }

}
